---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Disable swap immediately if active
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap permanently
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s.*)$'
    replace: '# \1'