---
- name: Prepare cloud platform nodes
  hosts: all
  become: true

  roles:
    - role: common
      tags:
        - common

    - role: container_runtime
      tags:
        - containerd

    - role: kubernetes
      tags:
        - kubernetes