---

# Prepare Ansible controller
- name: Prepare Ansible controller
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  roles:
    - role: ansible_controller
      tags:
        - controller
    - role: platform_services
      tags:
        - platform


# Prepare cloud platform nodes
- name: Prepare cloud platform nodes
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: common
      tags:
        - common

    - role: container_runtime
      tags:
        - containerd

    - role: kubernetes
      tags:
        - kubernetes


